package com.javaclimb.mapper;

import com.javaclimb.entity.GoodsOrderRelation;
import org.springframework.stereotype.Repository;

@Repository
public interface GoodsOrderRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_order_relation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_order_relation
     *
     * @mbg.generated
     */
    int insert(GoodsOrderRelation row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_order_relation
     *
     * @mbg.generated
     */
    int insertSelective(GoodsOrderRelation row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_order_relation
     *
     * @mbg.generated
     */
    GoodsOrderRelation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_order_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GoodsOrderRelation row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_order_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GoodsOrderRelation row);
}