package com.javaclimb.entity;

import javax.persistence.*;
import java.util.List;

/**
 *   商品详情表
 */
@Table(name = "goods_info")
public class GoodsInfo {
    /**
     * Database Column Remarks:
     *   主键
     */
    @Id // 声明是主键
    @GeneratedValue(strategy = GenerationType.IDENTITY) // 使用自增的规则
    private Long id;

    /**
     *   商品名称
     */
    @Column(name = "name")      // 强制为数据库字段
    private String name;

    /**
     *   价格
     */
    @Column(name = "price")      // 强制为数据库字段
    private Double price;

    /**
     *   商品折扣
     */
    @Column(name = "discount")      // 强制为数据库字段
    private Double discount;

    /**
     *   销量
     */
    @Column(name = "sales")      // 强制为数据库字段
    private Integer sales;

    /**
     *   点赞数
     */
    @Column(name = "likes")      // 强制为数据库字段
    private Integer likes;

    /**
     *   是不是推荐
     */
    @Column(name = "is_recommended")      // 强制为数据库字段
    private String isRecommended;

    /**
     *   库存
     */
    @Column(name = "stock")      // 强制为数据库字段
    private Integer stock;

    /**
     *   所属类别
     */
    @Column(name = "type_id")      // 强制为数据库字段
    private Long typeId;

    /**
     *   商品图片id，用英文逗号隔开
     */
    @Column(name = "fields")
    private String fields;

    /**
     *   所属卖家
     */
    @Column(name = "user_id")      // 强制为数据库字段
    private String userId;

    /**
     *   所属卖家权限等级
     */
    @Column(name = "access_level")      // 强制为数据库字段
    private Integer accessLevel;

    /**
     *   商品描述
     */
    @Column(name = "description")      // 强制为数据库字段
    private String description;


    /**
     * 商品图片具体地址列表
     */
    @Transient
    private List<Long> fileList;

    /**
     * 某用户是否已评价，评价状态
     */
    @Transient
    private String commentStatus;

    /**
     * 所属类别名称
     */
    @Transient
    private String typeName;

    /**
     * 所属卖家姓名(登录账号)
     */
    @Transient
    private String userName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.id
     *
     * @return the value of goods_info.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.id
     *
     * @param id the value for goods_info.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.name
     *
     * @return the value of goods_info.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.name
     *
     * @param name the value for goods_info.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.price
     *
     * @return the value of goods_info.price
     *
     * @mbg.generated
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.price
     *
     * @param price the value for goods_info.price
     *
     * @mbg.generated
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.discount
     *
     * @return the value of goods_info.discount
     *
     * @mbg.generated
     */
    public Double getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.discount
     *
     * @param discount the value for goods_info.discount
     *
     * @mbg.generated
     */
    public void setDiscount(Double discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.sales
     *
     * @return the value of goods_info.sales
     *
     * @mbg.generated
     */
    public Integer getSales() {
        return sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.sales
     *
     * @param sales the value for goods_info.sales
     *
     * @mbg.generated
     */
    public void setSales(Integer sales) {
        this.sales = sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.likes
     *
     * @return the value of goods_info.likes
     *
     * @mbg.generated
     */
    public Integer getLikes() {
        return likes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.likes
     *
     * @param likes the value for goods_info.likes
     *
     * @mbg.generated
     */
    public void setLikes(Integer likes) {
        this.likes = likes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.is_recommended
     *
     * @return the value of goods_info.is_recommended
     *
     * @mbg.generated
     */
    public String getIsRecommended() {
        return isRecommended;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.is_recommended
     *
     * @param isRecommended the value for goods_info.is_recommended
     *
     * @mbg.generated
     */
    public void setIsRecommended(String isRecommended) {
        this.isRecommended = isRecommended == null ? null : isRecommended.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.stock
     *
     * @return the value of goods_info.stock
     *
     * @mbg.generated
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.stock
     *
     * @param stock the value for goods_info.stock
     *
     * @mbg.generated
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.type_id
     *
     * @return the value of goods_info.type_id
     *
     * @mbg.generated
     */
    public Long getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.type_id
     *
     * @param typeId the value for goods_info.type_id
     *
     * @mbg.generated
     */
    public void setTypeId(Long typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.fields
     *
     * @return the value of goods_info.fields
     *
     * @mbg.generated
     */
    public String getFields() {
        return fields;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.fields
     *
     * @param fields the value for goods_info.fields
     *
     * @mbg.generated
     */
    public void setFields(String fields) {
        this.fields = fields == null ? null : fields.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.user_id
     *
     * @return the value of goods_info.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.user_id
     *
     * @param userId the value for goods_info.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.access_level
     *
     * @return the value of goods_info.access_level
     *
     * @mbg.generated
     */
    public Integer getAccessLevel() {
        return accessLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.access_level
     *
     * @param accessLevel the value for goods_info.access_level
     *
     * @mbg.generated
     */
    public void setAccessLevel(Integer accessLevel) {
        this.accessLevel = accessLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.description
     *
     * @return the value of goods_info.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.description
     *
     * @param description the value for goods_info.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    public List<Long> getFileList() {
        return fileList;
    }

    public void setFileList(List<Long> fileList) {
        this.fileList = fileList;
    }

    public String getCommentStatus() {
        return commentStatus;
    }

    public void setCommentStatus(String commentStatus) {
        this.commentStatus = commentStatus;
    }

    public String getTypeName() {
        return typeName;
    }

    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }
}