package com.javaclimb.entity;

/**
 * Database Table Remarks:
 *   订单商品的关系映射表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table goods_order_relation
 */
public class GoodsOrderRelation {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_order_relation.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   订单id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_order_relation.order_id
     *
     * @mbg.generated
     */
    private String orderId;

    /**
     * Database Column Remarks:
     *   所属商品id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_order_relation.goods_id
     *
     * @mbg.generated
     */
    private String goodsId;

    /**
     * Database Column Remarks:
     *   商品数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_order_relation.goods_quantity
     *
     * @mbg.generated
     */
    private String goodsQuantity;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_order_relation.id
     *
     * @return the value of goods_order_relation.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_order_relation.id
     *
     * @param id the value for goods_order_relation.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_order_relation.order_id
     *
     * @return the value of goods_order_relation.order_id
     *
     * @mbg.generated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_order_relation.order_id
     *
     * @param orderId the value for goods_order_relation.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_order_relation.goods_id
     *
     * @return the value of goods_order_relation.goods_id
     *
     * @mbg.generated
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_order_relation.goods_id
     *
     * @param goodsId the value for goods_order_relation.goods_id
     *
     * @mbg.generated
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId == null ? null : goodsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_order_relation.goods_quantity
     *
     * @return the value of goods_order_relation.goods_quantity
     *
     * @mbg.generated
     */
    public String getGoodsQuantity() {
        return goodsQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_order_relation.goods_quantity
     *
     * @param goodsQuantity the value for goods_order_relation.goods_quantity
     *
     * @mbg.generated
     */
    public void setGoodsQuantity(String goodsQuantity) {
        this.goodsQuantity = goodsQuantity == null ? null : goodsQuantity.trim();
    }
}