package com.javaclimb.entity;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 *   文件信息表
 */
@Table(name = "nx_system_file_info")
public class NxSystemFileInfo {
    /**
     *
     */
    @Id // 声明是主键
    @GeneratedValue(strategy = GenerationType.IDENTITY) // 使用自增的规则
    private Long id;

    /**
     *   原始文件名
     */
    private String originName;

    /**
     *   当前存储的文件名
     */
    private String fileName;

    /**
     *
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nx_system_file_info.id
     *
     * @param id the value for nx_system_file_info.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nx_system_file_info.origin_name
     *
     * @return the value of nx_system_file_info.origin_name
     *
     * @mbg.generated
     */
    public String getOriginName() {
        return originName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nx_system_file_info.origin_name
     *
     * @param originName the value for nx_system_file_info.origin_name
     *
     * @mbg.generated
     */
    public void setOriginName(String originName) {
        this.originName = originName == null ? null : originName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nx_system_file_info.file_name
     *
     * @return the value of nx_system_file_info.file_name
     *
     * @mbg.generated
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nx_system_file_info.file_name
     *
     * @param fileName the value for nx_system_file_info.file_name
     *
     * @mbg.generated
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }
}