package com.javaclimb.entity;

/**
 * Database Table Remarks:
 *   商品订单信息表
 *   DOUBLE里面，第一个参数是位数，第二个参数是精度
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table order_info
 */
public class OrderInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   订单号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.order_id
     *
     * @mbg.generated
     */
    private Long orderId;

    /**
     * Database Column Remarks:
     *   订单总价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.total_price
     *
     * @mbg.generated
     */
    private Double totalPrice;

    /**
     * Database Column Remarks:
     *   所属用户
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     * Database Column Remarks:
     *   用户权限等级
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.access_level
     *
     * @mbg.generated
     */
    private Integer accessLevel;

    /**
     * Database Column Remarks:
     *   联系地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.contact_address
     *
     * @mbg.generated
     */
    private String contactAddress;

    /**
     * Database Column Remarks:
     *   联系人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.contact_person
     *
     * @mbg.generated
     */
    private String contactPerson;

    /**
     * Database Column Remarks:
     *   联系电话
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.contact_Phone
     *
     * @mbg.generated
     */
    private String contactPhone;

    /**
     * Database Column Remarks:
     *   创建时间（）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.create_time
     *
     * @mbg.generated
     */
    private String createTime;

    /**
     * Database Column Remarks:
     *   订单状态（已付款已发货啥的）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.state
     *
     * @mbg.generated
     */
    private String state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.id
     *
     * @return the value of order_info.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.id
     *
     * @param id the value for order_info.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.order_id
     *
     * @return the value of order_info.order_id
     *
     * @mbg.generated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.order_id
     *
     * @param orderId the value for order_info.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.total_price
     *
     * @return the value of order_info.total_price
     *
     * @mbg.generated
     */
    public Double getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.total_price
     *
     * @param totalPrice the value for order_info.total_price
     *
     * @mbg.generated
     */
    public void setTotalPrice(Double totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.user_id
     *
     * @return the value of order_info.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.user_id
     *
     * @param userId the value for order_info.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.access_level
     *
     * @return the value of order_info.access_level
     *
     * @mbg.generated
     */
    public Integer getAccessLevel() {
        return accessLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.access_level
     *
     * @param accessLevel the value for order_info.access_level
     *
     * @mbg.generated
     */
    public void setAccessLevel(Integer accessLevel) {
        this.accessLevel = accessLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.contact_address
     *
     * @return the value of order_info.contact_address
     *
     * @mbg.generated
     */
    public String getContactAddress() {
        return contactAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.contact_address
     *
     * @param contactAddress the value for order_info.contact_address
     *
     * @mbg.generated
     */
    public void setContactAddress(String contactAddress) {
        this.contactAddress = contactAddress == null ? null : contactAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.contact_person
     *
     * @return the value of order_info.contact_person
     *
     * @mbg.generated
     */
    public String getContactPerson() {
        return contactPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.contact_person
     *
     * @param contactPerson the value for order_info.contact_person
     *
     * @mbg.generated
     */
    public void setContactPerson(String contactPerson) {
        this.contactPerson = contactPerson == null ? null : contactPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.contact_Phone
     *
     * @return the value of order_info.contact_Phone
     *
     * @mbg.generated
     */
    public String getContactPhone() {
        return contactPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.contact_Phone
     *
     * @param contactPhone the value for order_info.contact_Phone
     *
     * @mbg.generated
     */
    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone == null ? null : contactPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.create_time
     *
     * @return the value of order_info.create_time
     *
     * @mbg.generated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.create_time
     *
     * @param createTime the value for order_info.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.state
     *
     * @return the value of order_info.state
     *
     * @mbg.generated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.state
     *
     * @param state the value for order_info.state
     *
     * @mbg.generated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }
}